<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>Accept</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>Clone</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>Delete</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>Edit</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides>
    <deploymentStatus>Deployed</deploymentStatus>
    <description>Contains errors generated from the Relationships package during normal operations.  Errors can be viewed in the Relationships Settings tab.</description>
    <enableActivities>false</enableActivities>
    <enableEnhancedLookup>false</enableEnhancedLookup>
    <enableFeeds>false</enableFeeds>
    <enableHistory>false</enableHistory>
    <enableReports>true</enableReports>
    <fields>
        <fullName>Error_Date_Time__c</fullName>
        <description>Date &amp; time the error occurred</description>
        <externalId>false</externalId>
        <inlineHelpText>Date &amp; time the error occurred</inlineHelpText>
        <label>Error Date/Time</label>
        <required>false</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Record_Link__c</fullName>
        <description>A link to the record which caused the error, if available.</description>
        <externalId>false</externalId>
        <inlineHelpText>A link to the record which caused the error, if available.</inlineHelpText>
        <label>Error Record Link</label>
        <required>false</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Error_Stack_Trace__c</fullName>
        <description>Stack trace for the thrown error, if available at run time.</description>
        <externalId>false</externalId>
        <inlineHelpText>Stack trace for the thrown error, if available at run time.</inlineHelpText>
        <label>Error Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
        <visibleLines>3</visibleLines>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <description>Type of error that occurred</description>
        <externalId>false</externalId>
        <inlineHelpText>Type of error that occurred</inlineHelpText>
        <label>Error Type</label>
        <required>false</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Full_Error_Message__c</fullName>
        <description>Full text of the error message</description>
        <externalId>false</externalId>
        <inlineHelpText>Full text of the error message</inlineHelpText>
        <label>Full Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
        <visibleLines>3</visibleLines>
    </fields>
    <label>Relationship Error</label>
    <nameField>
        <displayFormat>E-{MMDDYY}-{00000000}</displayFormat>
        <label>Relationship Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Errors</pluralLabel>
    <searchLayouts/>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
